#ifndef EVENT_H
#define EVENT_H

#include <cstdint>
#include <vector>
#include <algorithm>
#include <unordered_map>
#include "types.hpp"

enum class EventType : uint8_t {
  None = 0,
  SetValue = 1,
  RemoveCandidate = 2
};

enum class ReasonId : uint8_t {
  Solver = 0,
  // naked subsets
  FullHouse,
  NakedSingle,
  NakedPair,
  NakedTriple,
  NakedQuad,
  // hidden subsets
  HiddenSingle,
  HiddenPair,
  HiddenTriple,
  HiddenQuad,
  // intersections
  PointingSet,
  PointingPair,
  PointingTriple,
  BoxLineReduction,
  ClaimingPair,
  ClaimingTriple,
  // basic fish
  XWing,
  Swordfish,
  Jellyfish,
  // finned and sashimi fish
  FinnedXWing,
  FinnedSwordfish,
  FinnedJellyfish,
  SashimiXWing,
  SashimiSwordfish,
  SashimiJellyfish,
  // advanced fish
  FrankenXWing,
  FrankenSwordfish,
  FrankenJellyfish,
  FinnedFrankenXWing,
  FinnedFrankenSwordfish,
  FinnedFrankenJellyfish,
  MutantXWing,
  MutantSwordfish,
  MutantJellyfish,
  FinnedMutantXWing,
  FinnedMutantSwordfish,
  FinnedMutantJellyfish,
  SiameseFish,
  KrakenFish,
  // single digit patterns
  SingleDigitPattern,
  Skyscraper,
  TwoStringKite,
  Crane,
  EmptyRectangle,
  // uniqueness
  UniqueRectangle,
  UniqueRectangleType1,
  UniqueRectangleType2,
  UniqueRectangleType3,
  UniqueRectangleType4,
  UniqueRectangleType5,
  UniqueRectangleType6,
  HiddenRectangle,
  AvoidableRectangle,
  BUGPlusOne,
  // wings
  XYWing,
  XYZWing,
  WXYZWing,
  WWing,
  // coloring
  SimpleColoring,
  SimpleColoringColorTrap,
  SimpleColoringColorWrap,
  _3DMedusa,
  _3DMedusaColorTrap,
  _3DMedusaColorWrap,
  _3DMedusaEmptiedCell,
  // chains
  RemotePair,
  XChain,
  XRing,
  XYChain,
  XYRing,
  AIC,
  AICType1,
  AICType2,
  AICType3,
  GroupedXChain,
  GroupedXRing,
  GroupedAIC,
  GroupedAICType1,
  GroupedAICType2,
  GroupedAICType3,
  // named wings and rings
  SWing,
  M2Wing,
  M3Wing,
  L1Wing,
  L2Wing,
  L3Wing,
  H1Wing,
  H2Wing,
  H3Wing,
  StrongWing,
  iWWing,
  DualWWing,
  iXYWing,
  iSWing,
  iM2Wing,
  iM3Wing,
  iL1Wing,
  iL2Wing,
  iL3Wing,
  iH1Wing,
  iH2Wing,
  iH3Wing,
  WRing,
  SRing,
  M2Ring,
  M3Ring,
  L1Ring,
  L2Ring,
  L3Ring,
  H1Ring,
  H2Ring,
  H3Ring,
  StrongRing,
  iWRing,
  DualWRing,
  iXYRing,
  iSRing,
  iM2Ring,
  iM3Ring,
  iL1Ring,
  iL2Ring,
  iL3Ring,
  iH1Ring,
  iH2Ring,
  iH3Ring,
  GroupedXYWing,
  GroupedWWing,
  GroupedSWing,
  GroupedM2Wing,
  GroupedM3Wing,
  GroupedL1Wing,
  GroupedL2Wing,
  GroupedL3Wing,
  GroupedH1Wing,
  GroupedH2Wing,
  GroupedH3Wing,
  GroupedStrongWing,
  GroupediWWing,
  GroupedDualWWing,
  GroupediXYWing,
  GroupediSWing,
  GroupediM2Wing,
  GroupediM3Wing,
  GroupediL1Wing,
  GroupediL2Wing,
  GroupediL3Wing,
  GroupediH1Wing,
  GroupediH2Wing,
  GroupediH3Wing,
  GroupedWRing,
  GroupedM2Ring,
  GroupedL1Ring,
  GroupedL2Ring,
  GroupedH2Ring,
  GroupedStrongRing,
  GroupediWRing,
  GroupediXYRing,
  GroupediSRing,
  GroupediM2Ring,
  GroupediM3Ring,
  GroupediL1Ring,
  GroupediL2Ring,
  GroupediL3Ring,
  GroupediH1Ring,
  GroupediH2Ring,
  GroupediH3Ring,
  // almost locked sets
  ALSXZ,
  ALSXZSinglyLinked,
  ALSXZDoublyLinked,
  ALSXYWing,
  ALSXYRing,
  ALSChain,
  ALSRing,
  SueDeCoq,
  DeathBlossom,
  // forcing
  ForcingChain,
  DigitForcingChain,
  NishioForcingChain,
  CellForcingChain,
  UnitForcingChain,
  ForcingNet,
  // exotic patterns
  Fireworks,
  TripleFireworks,
  QuadrupleFireworks,
};

NLOHMANN_JSON_SERIALIZE_ENUM_STRICT( ReasonId, {
  {ReasonId::Solver, "Solver"},
  {ReasonId::FullHouse, "Full House"},
  {ReasonId::NakedSingle, "Naked Single"},
  {ReasonId::NakedPair, "Naked Pair"},
  {ReasonId::NakedTriple, "Naked Triple"},
  {ReasonId::NakedQuad, "Naked Quad"},
  {ReasonId::HiddenSingle, "Hidden Single"},
  {ReasonId::HiddenPair, "Hidden Pair"},
  {ReasonId::HiddenTriple, "Hidden Triple"},
  {ReasonId::HiddenQuad, "Hidden Quad"},
  {ReasonId::PointingSet, "Pointing Set"},
  {ReasonId::PointingPair, "Pointing Pair"},
  {ReasonId::PointingTriple, "Pointing Triple"},
  {ReasonId::BoxLineReduction, "Box/Line Reduction"},
  {ReasonId::ClaimingPair, "Claiming Pair"},
  {ReasonId::ClaimingTriple, "Claiming Triple"},
  {ReasonId::XWing, "X-Wing"},
  {ReasonId::Swordfish, "Swordfish"},
  {ReasonId::Jellyfish, "Jellyfish"},
  {ReasonId::FinnedXWing, "Finned X-Wing"},
  {ReasonId::FinnedSwordfish, "Finned Swordfish"},
  {ReasonId::FinnedJellyfish, "Finned Jellyfish"},
  {ReasonId::SashimiXWing, "Sashimi X-Wing"},
  {ReasonId::SashimiSwordfish, "Sashimi Swordfish"},
  {ReasonId::SashimiJellyfish, "Sashimi Jellyfish"},
  {ReasonId::FrankenXWing, "Franken X-Wing"},
  {ReasonId::FrankenSwordfish, "Franken Swordfish"},
  {ReasonId::FrankenJellyfish, "Franken Jellyfish"},
  {ReasonId::FinnedFrankenXWing, "Finned Franken X-Wing"},
  {ReasonId::FinnedFrankenSwordfish, "Finned Franken Swordfish"},
  {ReasonId::FinnedFrankenJellyfish, "Finned Franken Jellyfish"},
  {ReasonId::MutantXWing, "Mutant X-Wing"},
  {ReasonId::MutantSwordfish, "Mutant Swordfish"},
  {ReasonId::MutantJellyfish, "Mutant Jellyfish"},
  {ReasonId::FinnedMutantXWing, "Finned Mutant X-Wing"},
  {ReasonId::FinnedMutantSwordfish, "Finned Mutant Swordfish"},
  {ReasonId::FinnedMutantJellyfish, "Finned Mutant Jellyfish"},
  {ReasonId::SiameseFish, "Siamese Fish"},
  {ReasonId::KrakenFish, "Kraken Fish"},
  {ReasonId::SingleDigitPattern, "Single Digit Pattern"},
  {ReasonId::Skyscraper, "Skyscraper"},
  {ReasonId::TwoStringKite, "Two-String Kite"},
  {ReasonId::Crane, "Crane"},
  {ReasonId::EmptyRectangle, "Empty Rectangle"},
  {ReasonId::UniqueRectangle, "Unique Rectangle"},
  {ReasonId::UniqueRectangleType1, "Unique Rectangle (Type 1)"},
  {ReasonId::UniqueRectangleType2, "Unique Rectangle (Type 2)"},
  {ReasonId::UniqueRectangleType3, "Unique Rectangle (Type 3)"},
  {ReasonId::UniqueRectangleType4, "Unique Rectangle (Type 4)"},
  {ReasonId::UniqueRectangleType5, "Unique Rectangle (Type 5)"},
  {ReasonId::UniqueRectangleType6, "Unique Rectangle (Type 6)"},
  {ReasonId::HiddenRectangle, "Hidden Rectangle"},
  {ReasonId::AvoidableRectangle, "Avoidable Rectangle"},
  {ReasonId::BUGPlusOne, "BUG+1"},
  {ReasonId::XYWing, "XY-Wing"},
  {ReasonId::XYZWing, "XYZ-Wing"},
  {ReasonId::WXYZWing, "WXYZ-Wing"},
  {ReasonId::WWing, "W-Wing"},
  {ReasonId::SimpleColoring, "Simple Coloring"},
  {ReasonId::SimpleColoringColorTrap, "Simple Coloring (Color Trap)"},
  {ReasonId::SimpleColoringColorWrap, "Simple Coloring (Color Wrap)"},
  {ReasonId::_3DMedusa, "3D Medusa"},
  {ReasonId::_3DMedusaColorTrap, "3D Medusa (Color Trap)"},
  {ReasonId::_3DMedusaColorWrap, "3D Medusa (Color Wrap)"},
  {ReasonId::_3DMedusaEmptiedCell, "3D Medusa (Emptied Cell)"},
  {ReasonId::RemotePair, "Remote Pair"},
  {ReasonId::XChain, "X-Chain"},
  {ReasonId::XRing, "X-Ring"},
  {ReasonId::XYChain, "XY-Chain"},
  {ReasonId::XYRing, "XY-Ring"},
  {ReasonId::AIC, "AIC"},
  {ReasonId::AICType1, "AIC (Type 1)"},
  {ReasonId::AICType2, "AIC (Type 2)"},
  {ReasonId::AICType3, "AIC (Type 3)"},
  {ReasonId::GroupedXChain, "Grouped X-Chain"},
  {ReasonId::GroupedXRing, "Grouped X-Ring"},
  {ReasonId::GroupedAIC, "Grouped AIC"},
  {ReasonId::GroupedAICType1, "Grouped AIC (Type 1)"},
  {ReasonId::GroupedAICType2, "Grouped AIC (Type 2)"},
  {ReasonId::GroupedAICType3, "Grouped AIC (Type 3)"},
  {ReasonId::SWing, "S-Wing"},
  {ReasonId::M2Wing, "M(2)-Wing"},
  {ReasonId::M3Wing, "M(3)-Wing"},
  {ReasonId::L1Wing, "L(1)-Wing"},
  {ReasonId::L2Wing, "L(2)-Wing"},
  {ReasonId::L3Wing, "L(3)-Wing"},
  {ReasonId::H1Wing, "H(1)-Wing"},
  {ReasonId::H2Wing, "H(2)-Wing"},
  {ReasonId::H3Wing, "H(3)-Wing"},
  {ReasonId::StrongWing, "Strong Wing"},
  {ReasonId::iWWing, "Inverted W-Wing"},
  {ReasonId::DualWWing, "Dual W-Wing"},
  {ReasonId::iXYWing, "Inverted XY-Wing"},
  {ReasonId::iSWing, "Inverted S-Wing"},
  {ReasonId::iM2Wing, "Inverted M(2)-Wing"},
  {ReasonId::iM3Wing, "Inverted M(3)-Wing"},
  {ReasonId::iL1Wing, "Inverted L(1)-Wing"},
  {ReasonId::iL2Wing, "Inverted L(2)-Wing"},
  {ReasonId::iL3Wing, "Inverted L(3)-Wing"},
  {ReasonId::iH1Wing, "Inverted H(1)-Wing"},
  {ReasonId::iH2Wing, "Inverted H(2)-Wing"},
  {ReasonId::iH3Wing, "Inverted H(3)-Wing"},
  {ReasonId::WRing, "W-Ring"},
  {ReasonId::SRing, "S-Ring"},
  {ReasonId::M2Ring, "M(2)-Ring"},
  {ReasonId::M3Ring, "M(3)-Ring"},
  {ReasonId::L1Ring, "L(1)-Ring"},
  {ReasonId::L2Ring, "L(2)-Ring"},
  {ReasonId::L3Ring, "L(3)-Ring"},
  {ReasonId::H1Ring, "H(1)-Ring"},
  {ReasonId::H2Ring, "H(2)-Ring"},
  {ReasonId::H3Ring, "H(3)-Ring"},
  {ReasonId::StrongRing, "Inverted Strong Ring"},
  {ReasonId::iWRing, "Inverted W-Ring"},
  {ReasonId::DualWRing, "Inverted Dual W-Ring"},
  {ReasonId::iXYRing, "Inverted XY-Ring"},
  {ReasonId::iSRing, "Inverted S-Ring"},
  {ReasonId::iM2Ring, "Inverted M(2)-Ring"},
  {ReasonId::iM3Ring, "Inverted M(3)-Ring"},
  {ReasonId::iL1Ring, "Inverted L(1)-Ring"},
  {ReasonId::iL2Ring, "Inverted L(2)-Ring"},
  {ReasonId::iL3Ring, "Inverted L(3)-Ring"},
  {ReasonId::iH1Ring, "Inverted H(1)-Ring"},
  {ReasonId::iH2Ring, "Inverted H(2)-Ring"},
  {ReasonId::iH3Ring, "Inverted H(3)-Ring"},
  {ReasonId::GroupedXYWing, "Grouped XY-Wing"},
  {ReasonId::GroupedWWing, "Grouped W-Wing"},
  {ReasonId::GroupedSWing, "Grouped S-Wing"},
  {ReasonId::GroupedM2Wing, "Grouped M(2)-Wing"},
  {ReasonId::GroupedM3Wing, "Grouped M(3)-Wing"},
  {ReasonId::GroupedL1Wing, "Grouped L(1)-Wing"},
  {ReasonId::GroupedL2Wing, "Grouped L(2)-Wing"},
  {ReasonId::GroupedL3Wing, "Grouped L(3)-Wing"},
  {ReasonId::GroupedH1Wing, "Grouped H(1)-Wing"},
  {ReasonId::GroupedH2Wing, "Grouped H(2)-Wing"},
  {ReasonId::GroupedH3Wing, "Grouped H(3)-Wing"},
  {ReasonId::GroupedStrongWing, "Grouped Strong Wing"},
  {ReasonId::GroupediWWing, "Grouped Inverted W-Wing"},
  {ReasonId::GroupedDualWWing, "Grouped Dual W-Wing"},
  {ReasonId::GroupediXYWing, "Grouped Inverted XY-Wing"},
  {ReasonId::GroupediSWing, "Grouped Inverted S-Wing"},
  {ReasonId::GroupediM2Wing, "Grouped Inverted M(2)-Wing"},
  {ReasonId::GroupediM3Wing, "Grouped Inverted M(3)-Wing"},
  {ReasonId::GroupediL1Wing, "Grouped Inverted L(1)-Wing"},
  {ReasonId::GroupediL2Wing, "Grouped Inverted L(2)-Wing"},
  {ReasonId::GroupediL3Wing, "Grouped Inverted L(3)-Wing"},
  {ReasonId::GroupediH1Wing, "Grouped Inverted H(1)-Wing"},
  {ReasonId::GroupediH2Wing, "Grouped Inverted H(2)-Wing"},
  {ReasonId::GroupediH3Wing, "Grouped Inverted H(3)-Wing"},
  {ReasonId::GroupedWRing, "Grouped W-Ring"},
  {ReasonId::GroupedM2Ring, "Grouped M(2)-Ring"},
  {ReasonId::GroupedL1Ring, "Grouped L(1)-Ring"},
  {ReasonId::GroupedL2Ring, "Grouped L(2)-Ring"},
  {ReasonId::GroupedH2Ring, "Grouped H(2)-Ring"},
  {ReasonId::GroupedStrongRing, "Grouped Inverted Strong Ring"},
  {ReasonId::GroupediWRing, "Grouped Inverted W-Ring"},
  {ReasonId::GroupediXYRing, "Grouped Inverted XY-Ring"},
  {ReasonId::GroupediSRing, "Grouped Inverted S-Ring"},
  {ReasonId::GroupediM2Ring, "Grouped Inverted M(2)-Ring"},
  {ReasonId::GroupediM3Ring, "Grouped Inverted M(3)-Ring"},
  {ReasonId::GroupediL1Ring, "Grouped Inverted L(1)-Ring"},
  {ReasonId::GroupediL2Ring, "Grouped Inverted L(2)-Ring"},
  {ReasonId::GroupediL3Ring, "Grouped Inverted L(3)-Ring"},
  {ReasonId::GroupediH1Ring, "Grouped Inverted H(1)-Ring"},
  {ReasonId::GroupediH2Ring, "Grouped Inverted H(2)-Ring"},
  {ReasonId::GroupediH3Ring, "Grouped Inverted H(3)-Ring"},
  {ReasonId::ALSXZ, "ALS-XZ"},
  {ReasonId::ALSXZSinglyLinked, "ALS-XZ Singly Linked"},
  {ReasonId::ALSXZDoublyLinked, "ALS-XZ Doubly Linked"},
  {ReasonId::ALSXYWing, "ALS-XY-Wing"},
  {ReasonId::ALSXYRing, "ALS-XY-Ring"},
  {ReasonId::ALSChain, "ALS Chain"},
  {ReasonId::ALSRing, "ALS Ring"},
  {ReasonId::SueDeCoq, "Sue-De-Coq"},
  {ReasonId::DeathBlossom, "Death Blossom"},
  {ReasonId::ForcingChain, "Forcing Chain"},
  {ReasonId::DigitForcingChain, "Digit Forcing Chain"},
  {ReasonId::NishioForcingChain, "Nishio Forcing Chain"},
  {ReasonId::CellForcingChain, "Cell Forcing Chain"},
  {ReasonId::UnitForcingChain, "Unit Forcing Chain"},
  {ReasonId::ForcingNet, "Forcing Net"},
  {ReasonId::Fireworks, "Fireworks"},
  {ReasonId::TripleFireworks, "Triple Fireworks"},
  {ReasonId::QuadrupleFireworks, "Quadruple Fireworks"},
})

// one operation = set value(s) or remove candidate(s) in a cell
struct Operation {
  Cell idx;
  DigitSet mask;

  bool operator==(const Operation &other) const {
    return idx == other.idx && mask == other.mask;
  }
};

// one source = a (cells, mask) pair explaining why the rule triggers
struct Source {
  CellSet cells;
  DigitSet mask;

  bool operator==(const Source &other) const {
    return cells == other.cells && mask == other.mask;
  }
};

class Event
{
public:
  Event();
  Event(EventType type, ReasonId reason);
  Event(EventType type, ReasonId reason, ReasonId detailedReason);

  EventType type;
  ReasonId reason;
  ReasonId detailedReason;

  std::vector<Operation> &getOperations();
  size_t getNumberOfOperations() const;
  void addOperation(Cell idx, Digit digit);
  void addOperation(Cell idx, DigitSet mask);

  std::array<std::vector<Source>, 4> &getSources();
  size_t getNumberOfSources() const;
  void addSource(Cell idx, Digit digit, int group);
  void addSource(Cell idx, DigitSet mask, int group);
  void addSource(CellSet cells, Digit digit, int group);
  void addSource(CellSet cells, DigitSet mask, int group);

private:
  friend class EventQueue;
  // an event is a set of multiple operations
  std::vector<Operation> ops;
  // an event can be described by more sources, divided in four groups
  std::array<std::vector<Source>, 4> sources;
};

#endif // EVENT_H
