  // must follow the same order in Event.hpp
  const WASM_REASON = [
    "Solver",
    "Full House",
    "Naked Single",
    "Naked Pair",
    "Naked Triple",
    "Naked Quad",
    "Hidden Single",
    "Hidden Pair",
    "Hidden Triple",
    "Hidden Quad",
    "Pointing Pair",
    "Pointing Triple",
    "Claiming Pair",
    "Claiming Triple",
    "X-Wing",
    "Swordfish",
    "Jellyfish",
    "Finned X-Wing",
    "Finned Swordfish",
    "Finned Jellyfish",
    "Franken Fish",
    "Mutant Fish",
    "Siamese Fish",
    "Finned Franken Fish",
    "Finned Mutant Fish",
    "XY-Wing",
    "XYZ-Wing",
    "WXYZ-Wing",
    "Chute Remote Pair",
    "W-Wing",
    "Unique Rectangle",
    "Hidden Rectangle",
    "Avoidable Rectangle",
    "BUG+1",
    "Simple Coloring",
    "3D Medusa",
    "Skyscraper",
    "Two-String Kite",
    "Crane",
    "Empty Rectangle",
    "Remote Pair",
    "X-Chain",
    "XY-Chain",
    "Alternating Inference Chain",
    "Grouped Alternating Inference Chain",
    "Sue-de-Coq",
    "ALS-XZ",
    "ALS-XY",
    "Death Blossom",
  ];